### ISSUE TITLE
DB Backups design

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/sys#109]
NOTE: this is a design issue and we need to gather opinions on this...

Initially i was thinking of backing up to a cloud storage.

Now i think it might be much smarter to do streaming backups from one instance to another.

Why ?

- Because then we are designing for HA from the start. SO there is really no such thing as a backup.
- If Master falls over, then slave is sitting there ready to go. Its just a matter of repointing the DNS or the Proxy ( which we dont use yet)
- It will give use the ability to scale out and split reads to the slaves, and writes to the master.
- Its really the start of a CDC system, because you want to have a source of the master and a sink of the slaves.
- Uer dont need to standup a cloud bucket. They just need to standup 2 or more of the same thing which is always easier
- DB Migrations. Will need to operate on all instances.. Needs consideration of how we surface this. The CLI currently i think has backups in it ?

How to do it ?

Badger support streaming backups. I think we use it at the moment, but not sure..

Config aspects
- we dont have the concept of Master slave in the system, and so maybe we need to introduce  it.

**Comment by AppliNH** [comment]
Maybe considering MinIO for saving backups would be interesting ?
It's made out of Go

https://github.com/minio/minio
