### ISSUE TITLE
Refactor Flutter code, so we are setup for mod and test code.

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/sys#35]
We need to start to get some basic testing going on the flutter code.

Before starting any of this, lets discuss first so we have the game plan correct

But at what point ? And also from looking at things i think we might have to move some code around into sys-shared first.

First i can see that we need to move some code to sys-share.
Doing this now is a good idea BEFORE we write too much mod level code.

sys/sys-core/service/flu is code that is used by by everyone. Its GUI related code. so it seems we need to move this to sys-shared ?
sys-share/sys-core/service/flu/lib/rpc has all the grpc generated code. 
SO move the flutter code from sys/sys-core/service/flu --> sys-share/sys-core/service/flu/lib/pkg
- I think "pkg" is a good name, because it matches what we did in sys-share/sys-account/service/flu/lib/pkg and sys-share/sys-account/service/flu/lib/rpc

- also sys/sys-core/service/flu/api is redundant now i think.
- also sys/sys-core/service/flu/account is redundant, but we will need hive cache so you can move it to sys-share/sys-core/service/flu/lib/pkg, and comment it out for now. We can come back to it later.
- also sys/sys-core/service/flu/widget is used.
- also sys/sys-core/service/flu/setting can get rid of the "src" dir
- also sys/sys-core/service/flu/i18n is important.

---

Once this is done change the paths for the mod-survey etc

---

Then we can revisit how to test. Maybe we go for RiverPod before we write too much mod code.
Anyway we shoudl discuss this.

**Comment by gutterbacon** [comment]
Close this please

**Comment by joe-getcouragenow** [comment]
Get shared/sys-core bin and examples building from makefile.

protos. dont worry about them not being correct. 

Main thing is to wire up everything so CI can run and build.
