### ISSUE TITLE
benchmark to exercise genji / sys-accounts

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/sys#36]
Commit the existing bench. 

Main thing right now is working out if its out code or genji code.
So we can give quality feedback to the genji team.

Lets not use TLS yet, as per other Issue: https://github.com/getcouragenow/sys/issues/34

We can discuss how best to get the benchmark code working with sys accounts then.

**Comment by gutterbacon** [comment]
Can be closed now

**Comment by joe-getcouragenow** [comment]
Next steps

Make the Users and Concurrent DB connections a flag param.
Wire up the make file

**Comment by joe-getcouragenow** [comment]
Then after that we will make the benchmark part of the CLI

- SO can run many clients onto many servers ( v2 and v3). The CLI has no knowledge of where the DB is, and the Server
