### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/sys#47]
JSONET config first
- main
- mod
   - mod-dummy
   - not the other mods
- sys
- sys-share

--

DB Proto and Security

Now we revisit how we access the DB BEFORE we do the DB Refactor

- RPC Authz
  - How can we enforce authz when running in GO an GO GRPC modes ?
- Db Authz
 - How when running in V2 single binary mode can we enforce mods not acessing sys-accounts data ?

--

DB refactor

- config drives the DB path/name.
- moves ALL of sys-core to sys-shared/sys-core
   -  DB pkg, etc
   - Config
 - mod-dummy
   - not others yet
   - make it have it own DB
   - Make it work for v2 and v3
      - when v2, shares the core DB
      - when v3, has its own DB
   - CLI
      - Uses the Server Services and so will naturally use the right DB.

**Comment by gutterbacon** [comment]
Note to self: see https://github.com/getcouragenow/shared-doc/blob/master/content/roadmap/ROADMAP.md

**Comment by joe-getcouragenow** [comment]
all done :)
