### ISSUE TITLE
/Users/apple/workspace/go/src/github.com/joe-getcouragenow/sys/sys-account. 

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/sys#60]
make this-ex-server-run
Running Example Server
cd ./bin-all/server && rm -rf getcouragenow.db && ./main
2020/10/21 09:32:39 WARNING: proto: file "pb.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

FATA[0000] DB is not initialized, please call InitDatabase first 
make: *** [this-ex-server-run] Error 1
➜  sys-account git:(master) ✗

**Comment by gutterbacon** [comment]
#51
